### ISSUE TITLE
sqlite_datetime_fix: no guarantee that value is not a string

### ISSUE THREAD

**Issue by scraperdragon** [pudo/dataset#96] opened 2014-06-04 09:57 UTC
Inside `sqlite_datetime_fix`'s `process_bind_param`, https://github.com/pudo/dataset/blob/master/dataset/persistence/util.py#L79 , it's possible for value to be a string (`str`, `unicode`). This causes dataset to crash.

**Comment by pudo** [comment] 2015-05-21 15:18
I've done something harsh: since I cannot even remember why we introduced ``sqlite_datetime_fix`` in the first place and since it appears to messy with virtually any use case except somehow magically casting datetimes into an int column, I've killed it in 01f85c11b908ed90d7fb3d47859982a18011ee43. Let's see what dies, but it's not tested.

**Comment by eads** [comment] 2015-05-21 17:50
I tested and found that the latest fix reintroduces the previous error.

**Comment by pudo** [comment] 2015-05-21 20:33
I'm not actually entirely sure what the intended outcome of putting a string into a datetime column is: do you want me to run ``dateutil.parser`` on it so that it guesses the date representation? Seems like a bit too much magic for my taste but I'm happy to be convinced otherwise.

**Comment by eads** [comment] 2015-05-21 20:45
As far as I understand, this is just a dupe of #97, but I might be being dense. The string is coming from a query result, so the round-trip fails. 

Using dateutil.parser seems like too much overhead and magic to me, too.

**Comment by pudo** [comment] 2015-05-21 20:48
Ok, got it. Closing in favour of #97. Thanks for the useful example there.

**Closed by pudo** 2015-05-21 20:48 UTC
