### ISSUE TITLE
Python3.4 sqllite datafreeze do not work (startswith first arg must be bytes or a tuple of bytes, not str)

### ISSUE THREAD

**Issue by mihhailnovik** [pudo/dataset#111] opened 2014-12-20 02:43 UTC
version:0.5.5
os: debian
python: 3.4

code:

```
import dataset
if __name__ == '__main__':
    db = dataset.connect('sqlite:///mydatabase.db')
    table = db['user']
    table.insert(dict(name='John Doe', age=46, country='China'))
    result = db['user'].all()
    dataset.freeze(result, format='json', filename='users.json')
```

result is:

```
/usr/bin/python3.4 /home/m1/programming/python/test_dataset/main.py
Traceback (most recent call last):
  File "/home/m1/programming/python/test_dataset/main.py", line 10, in <module>
    dataset.freeze(result, format='json', filename='users.json')
  File "/usr/local/lib/python3.4/dist-packages/dataset-0.5.5-py3.4.egg/dataset/freeze/app.py", line 92, in freeze
    return freeze_export(Export({}, kw), result=records)
  File "/usr/local/lib/python3.4/dist-packages/dataset-0.5.5-py3.4.egg/dataset/freeze/app.py", line 104, in freeze_export
    serializer.serialize()
  File "/usr/local/lib/python3.4/dist-packages/dataset-0.5.5-py3.4.egg/dataset/freeze/format/common.py", line 90, in serialize
    self.write(self.file_name(row), row)
  File "/usr/local/lib/python3.4/dist-packages/dataset-0.5.5-py3.4.egg/dataset/freeze/format/common.py", line 63, in file_name
    if not path.startswith(self._prefix):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

Process finished with exit code 1
```

As i understood `dataset/freeze/format/common.py:46` returns array of bytes and because of that we call `bytes.startswith()` not `string.startwith()`

After i did:

```
freeze/format/common.py:
54: - return os.path.realpath(path.encode(enc, 'replace'))
54: + return os.path.realpath(path)
```

it passes the place it failed, but got another exception 'str' does not support the buffer interface
 
```
freeze/format/fjson.py:
49: - fh.write(data)
49:+ fh.write(bytes(data, 'UTF-8'))
```

**Comment by pudo** [comment] 2015-05-23 13:12
I cannot reproduce this issue and believe that it may be related to an invalid setting of the locale on your local machine. Please submit a dump of your environment variables if this still happens with the latest ``master`` or dataset. Closing until then.

**Closed by pudo** 2015-05-23 13:12 UTC
