### ISSUE TITLE
Memory leak when iterating over DB with .all()

### ISSUE THREAD

**Issue by Jwink3101** [pudo/dataset#226] opened 2017-09-30 19:04 UTC
My dataset-backed website tends go grow in memory over time and I *think* I finally traced it to dataset and my search function which iterates the entire DB (not the best method, I know).

I only know a little bit of SQL, but I created the example below to demonstrate the problem. It uses [`memory_profiler`](https://github.com/fabianp/memory_profiler). Also note that you do not have to run the `make_db()` more than once (it is kind of slow). I also include a quick sanity check that both methods are iterating over the entire DB. 

I ran this with: (python 3.6.2) with the latest dataset (1.0.2)

    $ python3 -m memory_profiler testmem.py

You will see that the first iteration through dataset adds a lot of memory and then the next ones add too (and it is never cleaned up). On the flip side, the iteration through the sqlite version doesn't change the memory (at all) and through the dataset `query` only adds memory the first time.

(I should note that these are not 100% consistent. Run it a few times)

````python
from memory_profiler import profile # pip install memory_profiler

import sys
if sys.version_info[0]>2:
    xrange = range
    unicode = str

import os
import random
import dataset
import sqlite3

DBname = 'test.db'

N = 5000;

LI = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."""
LI = LI.split()

def make_db():
    # delete it
    try:
        os.remove(DBname)
    except OSError:
        pass
    
    DB = dataset.connect('sqlite:///' + DBname)
    tab = DB['tab']
    
    def rows(N): # Iterator to yield the next item
        for nn in range(N):
            item = {'N':nn}
            item['text'] = ' '.join(random.choice(LI) for _ in range(500))     
            yield item
    
    tab.insert_many(rows(N))
    DB.commit()    

@profile
def test_iter_dataset(tab):
    count = 0
    all_iterator = tab.all()
    for page in all_iterator:
        count += len(page['text']) # Make sure it is querying all
    
    print(count)

@profile
def test_iter_dataset_sql(DB):
    count = 0
    for page in DB.query('SELECT * from tab'):
        count += len(page['text']) # Make sure it is querying all

    print(count)

@profile
def test_iter_sqlite(cursor):
    count = 0
    for page in cursor.execute('SELECT * from tab'):
        count += len(page[2]) # Make sure it is querying all

    print(count)
    

if __name__ == '__main__':
    make_db() # Just run once
    
    # Test with the same DB
    DB = dataset.connect('sqlite:///' + DBname)
    tab = DB['tab']
    for ii in range(3):
        print('dataset {} ---------'.format(ii))
        test_iter_dataset(tab)
        print('dataset {} +++++++++'.format(ii))
    
    DB2 = dataset.connect('sqlite:///' + DBname)
    for ii in range(3):
        print('dataset sql {} ---------'.format(ii))
        test_iter_dataset_sql(DB2)
        print('dataset sql {} +++++++++'.format(ii))
    
    DB3 = sqlite3.connect(DBname)
    cursor = DB3.cursor()
    for ii in range(3):
        print('sqlite {} ---------'.format(ii))
        test_iter_sqlite(cursor)
        print('sqlite {} +++++++++'.format(ii))
    
````

**Comment by matthewswain** [comment] 2017-12-11 12:34
Hi @Jwink3101 .

I ran your script to reproduce and the memory does climb, but that seems to be because you're creating new variables which don't go out of scope until the end of the program (DB, DB2, DB3). 

E.g. if you explicitly remove those variables from scope then there doesn't appear to be a memory leak:
```
import gc

if __name__ == '__main__':
    make_db() # Just run once
    
    # Test with the same DB
    DB = dataset.connect('sqlite:///' + DBname)
    tab = DB['tab']
    for ii in range(3):
        print('dataset {} ---------'.format(ii))
        test_iter_dataset(tab)
        print('dataset {} +++++++++'.format(ii))
    # remove variable from scope
    del DB
    # call garbage collection so we're not waiting for the interpreter
    gc.collect()
    
    DB2 = dataset.connect('sqlite:///' + DBname)
    for ii in range(3):
        print('dataset sql {} ---------'.format(ii))
        test_iter_dataset_sql(DB2)
        print('dataset sql {} +++++++++'.format(ii))
    # remove variable from scope
    del DB
    # call garbage collection so we're not waiting for the interpreter
    gc.collect()
    
    DB3 = sqlite3.connect(DBname)
    cursor = DB3.cursor()
    for ii in range(3):
        print('sqlite {} ---------'.format(ii))
        test_iter_sqlite(cursor)
        print('sqlite {} +++++++++'.format(ii))
    # remove variable from scope
    del DB
    # call garbage collection so we're not waiting for the interpreter
    gc.collect()
```
And also if you call it in a loop, so that DB goes out of scope at the end of each iteration, again I don't see a memory leak:
```
import gc

if __name__ == '__main__':
    make_db() # Just run once
    
    for j in range(1000):
        gc.collect() # call garbage collection so we're not waiting for the interpreter
        # Test with the same DB
        DB = dataset.connect('sqlite:///' + DBname)
        tab = DB['tab']
        for ii in range(3):
            print('dataset {} ---------'.format(ii))
            test_iter_dataset(tab)
            print('dataset {} +++++++++'.format(ii))
```
Does this reflect what's happening in your app?

**Closed** 2020-01-11 14:01 UTC
