### ISSUE TITLE
drop_column() fails with OperationalError 

### ISSUE THREAD

**Issue by mgaitan** [pudo/dataset#131] opened 2015-06-25 22:40 UTC
```python
In [37]: publications.columns
Out[37]: ['id', 'title', 'journal', 'year', 'authors', 'doi', 'cited_by', 'not_found']

In [38]: publications.drop_column("not_found")
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1138                         parameters,
-> 1139                         context)
   1140         except Exception as e:

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    449     def do_execute(self, cursor, statement, parameters, context=None):
--> 450         cursor.execute(statement, parameters)
    451 

OperationalError: near "DROP": syntax error

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
<ipython-input-38-3f86de9110c9> in <module>()
----> 1 publications.drop_column("not_found")

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/dataset/persistence/table.py in drop_column(self, name)
    258                 self.database.op.drop_column(
    259                     self.table.name,
--> 260                     name
    261                 )
    262                 self.table = self.database.update_table(self.table.name)

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/alembic/operations.py in drop_column(self, table_name, column_name, **kw)
    648             table_name,
    649             self._column(column_name, NULLTYPE),
--> 650             **kw
    651         )
    652 

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/alembic/ddl/impl.py in drop_column(self, table_name, column, schema, **kw)
    177 
    178     def drop_column(self, table_name, column, schema=None, **kw):
--> 179         self._exec(base.DropColumn(table_name, column, schema=schema))
    180 
    181     def add_constraint(self, const):

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/alembic/ddl/impl.py in _exec(self, construct, execution_options, multiparams, params)
    120             if execution_options:
    121                 conn = conn.execution_options(**execution_options)
--> 122             return conn.execute(construct, *multiparams, **params)
    123 
    124     def execute(self, sql, execution_options=None):

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/base.py in execute(self, statement, *multiparams, **params)
   1987 
   1988         connection = self.contextual_connect(close_with_result=True)
-> 1989         return connection.execute(statement, *multiparams, **params)
   1990 
   1991     def scalar(self, statement, *multiparams, **params):

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/base.py in execute(self, object, *multiparams, **params)
    912                 type(object))
    913         else:
--> 914             return meth(self, multiparams, params)
    915 
    916     def _execute_function(self, func, multiparams, params):

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py in _execute_on_connection(self, connection, multiparams, params)
     66 
     67     def _execute_on_connection(self, connection, multiparams, params):
---> 68         return connection._execute_ddl(self, multiparams, params)
     69 
     70     def execute(self, bind=None, target=None):

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/base.py in _execute_ddl(self, ddl, multiparams, params)
    966             compiled,
    967             None,
--> 968             compiled
    969         )
    970         if self._has_events or self.engine._has_events:

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1144                 parameters,
   1145                 cursor,
-> 1146                 context)
   1147 
   1148         if self._has_events or self.engine._has_events:

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1339                 util.raise_from_cause(
   1340                     sqlalchemy_exception,
-> 1341                     exc_info
   1342                 )
   1343             else:

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/util/compat.py in raise_from_cause(exception, exc_info)
    186             exc_info = sys.exc_info()
    187         exc_type, exc_value, exc_tb = exc_info
--> 188         reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
    189 else:
    190     exec("def reraise(tp, value, tb=None, cause=None):\n"

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    179             value.__cause__ = cause
    180         if value.__traceback__ is not tb:
--> 181             raise value.with_traceback(tb)
    182         raise value
    183 

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1137                         statement,
   1138                         parameters,
-> 1139                         context)
   1140         except Exception as e:
   1141             self._handle_dbapi_exception(

/home/tin/.virtualenvs/curso/lib/python3.4/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    448 
    449     def do_execute(self, cursor, statement, parameters, context=None):
--> 450         cursor.execute(statement, parameters)
    451 
    452     def do_execute_no_params(self, cursor, statement, context=None):

OperationalError: (sqlite3.OperationalError) near "DROP": syntax error [SQL: 'ALTER TABLE publication DROP COLUMN not_found']

In [39]: !pip freeze | grep dataset
dataset==0.6.0
```

**Comment by gka** [comment] 2015-06-26 01:45
Can you add a [test case](https://github.com/pudo/dataset/blob/master/test/test_persistence.py) that reproduces the bug?

**Comment by mgaitan** [comment] 2015-06-26 15:45
I discovered that sqlite hasn't support for "DROP column" 

http://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite 




 https://bitbucket.org/zzzeek/alembic/issue/21/column-renames-not-supported-on-sqlite#comment-13511426

di

**Comment by mgaitan** [comment] 2015-06-26 15:58
@gka there a simple test. 

I found that it isn't a "bug" but a [missing feature in sqlite](http://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite)

So the common workaround is create a new temporary data and insert each row after deleting the column, then delete the original table and rename the temporary one. 

I've mocked up something like this (just pseudocode)

```

  def drop_column(self, name):
        self._check_dropped()
        if self.database.engine.name == 'sqlite':
            return self._drop_column_sqlite(name)
       ....

    def _drop_column_sqlite(self, name):
        name_tmp = self.table.name + '_tmp'
        table_tmp = self.database[name_tmp]
        for row in self:
                del row[name]
                table_tmp.insert(row)
        self.drop()
        self.database.op.rename_table(name_tmp, name)
```

also, this issue seems to be related, but I don't understand the given solution. 
https://bitbucket.org/zzzeek/alembic/issue/21/column-renames-not-supported-on-sqlite

**Comment by pudo** [comment] 2015-06-29 09:20
Thanks for the report and the test. I wonder what our options are, I see two: wrap this failure in a nicer error to make it clear it's a backend issue, or implement the whole ``DROP TABLE`` dance. My preference would be the former, since dropping columns is a pretty fringe thing to begin with. What do people think?

**Comment by pudo** [comment] 2016-02-12 17:13
Closing, as this is an upstream issue.

**Closed by pudo** 2016-02-12 17:13 UTC

**Comment by void4** [comment] 2021-12-02 00:46
It would be nice if the workaround was implemented anyway
