### ISSUE TITLE
db close

### ISSUE THREAD

**Issue by valbanese** [pudo/dataset#135] opened 2015-07-20 11:08 UTC
I'm not seeing a close method on the database API.  What's the proper process to handle a close?  Thanks for your efforts with this.

**Comment by pudo** [comment] 2015-07-21 14:37
Nope, that is indeed missing :( Would you be up for doing a pull request? I guess it's just a matter of disposing of the connection pool used by SQLAlchemy, since the handling (and closing) of actual connections used in transactions with the database is handled automatically on that layer.

**Comment by valbanese** [comment] 2015-07-21 14:47
Yes, I’d like to pitch in and help with this. I’m using Dataset more and more in my regular work.  Thanks again for you efforts.

Vince

Vince Albanese / Managing Partner 
valbanese@amplefi.com <mailto:valbanese@amplefi.com> / 727-366-7070

Amplefi 
http://www.amplefi.com <http://www.amplefi.com/>

**Closed** 2016-02-12 17:20 UTC

**Comment by OrganicIrradiation** [comment] 2016-05-11 22:58
I know this is closed, but it's a feature I would really like to see implemented. I just recently had to deal with overloading my allocated connections with pythonanywhere and need to be able to close the connection after writing to the database:

  * https://help.pythonanywhere.com/pages/ManagingDatabaseConnections/

**Comment by pudo** [comment] 2016-05-12 07:28
Ok, Sounds good! Please do submit a PR!

**Comment by OrganicIrradiation** [comment] 2016-05-27 18:27
I'm trying to figure out how to best address it, but I'm not familiar with SQLAlchemy. Quick background: I am trying to setup a program that can access a MySQL database on pythonanywhere.com but having issues because dataset does not appear to close the MySQL connection, meaning that each time someone tries to access the page with Flask leads to another connection which persists until the MySQL timeout. Here's a quick test with a simple app that inserts a random number into the database (note username and password need to be filled):

 1. Signed up for a beginner's account
 2. Initialize MySQL
 3. Create a new web app with Flask 0.9 and Python 2.7
 4. Add the following code to flask_app.py:

        from datetime import datetime
        from flask import Flask
        import dataset
        import random
        
        app = Flask(__name__)
        
        # Get the database information from the configuration file
        DEBUG = False
        if DEBUG:
            database_url ='sqlite:///debug_database.db'
        else:
            ur = 'USERNAME'
            pw = 'PASSWORD'
            database_url = 'mysql://{0}:{1}@{0}.mysql.pythonanywhere-services.com/{0}$default'.format(ur, pw)
        
        
        @app.route("/")
        def index():
            randnum = random.randint(0, 100000)
            db = dataset.connect(database_url)
            table = db['test_data']
            stored = dict(dt=str(datetime.now()), randnum=randnum)
            table.insert(stored)
            retrieved = table.find_one(randnum=randnum)
            return 'Stored: {}, Retrieved: {}'.format(stored, retrieved)
        
        
        if __name__ == "__main__":
            app.run(debug=DEBUG)

 5. Reload the [web app](http://testdataset.pythonanywhere.com) via the online console.

The app runs fine a few times but then I get a 500 Internal Server Error with the following stack trace in the error log:

    SyntaxError: invalid syntax
    2016-05-27 18:09:55,443 :Exception on / [GET]
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/testdataset/mysite/flask_app.py", line 22, in index
        db = dataset.connect(database_url)
      File "/usr/local/lib/python2.7/dist-packages/dataset/__init__.py", line 35, in connect
        return Database(url, schema=schema, reflectMetadata=reflectMetadata)
      File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/database.py", line 52, in __init__
        self.metadata.reflect(self.engine)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/schema.py", line 2762, in reflect
        with bind.connect() as conn:
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1641, in connect
        return self._connection_cls(self, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 59, in __init__
        self.__connection = connection or engine.raw_connection()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1699, in raw_connection
        return self.pool.unique_connection()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 220, in unique_connection
        return _ConnectionFairy(self).checkout()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 431, in __init__
        rec = self._connection_record = pool._do_get()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 788, in _do_get
        con = self._create_connection()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 225, in _create_connection
        return _ConnectionRecord(self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 318, in __init__
        self.connection = self.__connect()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 379, in __connect
        connection = self.__pool._creator()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 80, in connect
        return dialect.connect(*cargs, **cparams)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 283, in connect
        return self.dbapi.connect(*cargs, **cparams)
      File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
        return Connection(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 193, in __init__
        super(Connection, self).__init__(*args, **kwargs2)
    OperationalError: (OperationalError) (1226, "User 'testdataset' has exceeded the 'max_user_connections' resource (current value: 3)") None None

Any idea how to address this? I tried to add the following to close the database connection before the return, but to no avail:

    if hasattr(db.local, 'connection'):
        db.local.connection.close()
        del db.local.connection

**Comment by OrganicIrradiation** [comment] 2016-05-27 18:37
Figured it out... Need to call this rather than closing the local connection:

    db.engine.dispose()

**Comment by Anntoin** [comment] 2017-04-05 16:15
It seems like this is something that dataset should handle transparently, and the current behaviour isn't ideal and could lead to overloading a db with stale connections.

**Comment by stefanw** [comment] 2017-04-06 11:35
@OrganicIrradiation You're opening a new database connection on every request in your `index` view, that's why you're exceeding the "`'max_user_connections' resource`".

This has nothing to do with dataset. Please follow the [instructions on how to handle database connections when running a Flask server](http://flask.pocoo.org/docs/0.12/tutorial/dbcon/). [Also have a look at this example code](https://github.com/pallets/flask/blob/master/examples/flaskr/flaskr/flaskr.py).

**Comment by OrganicIrradiation** [comment] 2017-04-06 16:18
@stefanw As I noted in my response (https://github.com/pudo/dataset/issues/135#issuecomment-222222277), I was able to close the database connection at the end of the index() function using dataset by calling ```db.engine.dispose()```. Since I was using dataset to manage the database connection (and not sqlite3/flask), I would argue the issue **does** concern dataset. Neither of the resources you linked appear to be directly applicable to the database access method in this issue.

I'm not sure what the current status of this issue is (I don't have the code running on the setup now), but presumably this [code snippet in the quickstart](https://dataset.readthedocs.io/en/latest/quickstart.html#using-transactions) should open a connection to the database and close the connection once the context ```__exit__```'s:

```python
with dataset.connect() as tx:
    tx['user'].insert(dict(name='John Doe', age=46, country='China'))

# database connection should be closed at this point
```

I would expect the database connection to close after completion of the ```with``` statement. If it does not, then this is unexpected behavior.
